schema_version = "1.0.0"

id = "synchronize_workspaces"
version = "1.13.0"
name = "Synchronize Workspaces"
tagline = "Synchronize 3D views between workspaces"
maintainer = "Michael Soluyanov <to@multlabs.com>"

type = "add-on"

tags = ["3D View", "User Interface"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-2.0-or-later",
]

